package us.webmy.core.internal.theme

import us.webmy.core.theme.ColorsPalette
import androidx.compose.material3.ColorScheme

internal fun ColorsPalette.toMaterialColorScheme(): ColorScheme = ColorScheme(
    primary = textAndIconsPrimary,
    onPrimary = textAndIconsInversePrimary,
    primaryContainer = backgroundTertiary,
    onPrimaryContainer = textAndIconsPrimary,
    inversePrimary = textAndIconsInversePrimary,
    secondary = textAndIconsSecondary,
    onSecondary = textAndIconsInversePrimary,
    secondaryContainer = backgroundSecondary,
    onSecondaryContainer = textAndIconsPrimary,
    tertiary = textAndIconsTertiary,
    onTertiary = textAndIconsInversePrimary,
    tertiaryContainer = backgroundTertiary,
    onTertiaryContainer = textAndIconsPrimary,
    background = backgroundPrimary,
    onBackground = textAndIconsPrimary,
    surface = backgroundPrimary,
    onSurface = textAndIconsPrimary,
    surfaceVariant = backgroundSecondary,
    onSurfaceVariant = textAndIconsSecondary,
    surfaceTint = textAndIconsTertiary,
    inverseSurface = backgroundInverse,
    inverseOnSurface = textAndIconsInversePrimary,
    error = error,
    onError = textAndIconsInversePrimary,
    errorContainer = error,
    onErrorContainer = textAndIconsInversePrimary,
    outline = appliedStroke,
    outlineVariant = appliedSeparator,
    scrim = appliedOverlay,
    surfaceBright = backgroundPrimary,
    surfaceDim = backgroundSystem,
    surfaceContainer = backgroundSecondary,
    surfaceContainerHigh = backgroundTertiary,
    surfaceContainerHighest = backgroundTertiary,
    surfaceContainerLow = backgroundSecondary,
    surfaceContainerLowest = backgroundPrimary,
)
